tags:
  - name: security
    description: login and logout api
  - name: users
    description: users API
  - name: scoring
    description: scoring API

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /login:
    post:
      description: 'Return token for authorized users <br /> email: ***aaa@noeticworld.com*** <br /> password: ***q1w2e3r4***'
      summary: ''
      tags: [security]
      consumes:
        - 'application/json'
      parameters:
        - name: 'login'
          in: 'body'
          required: true
          description: 'Login Payload'
          schema:
            $ref: '#/definitions/login'
      responses:
        200:
          description: Successful login
          schema:
            $ref: '#/definitions/loginSuccess'
        400:
          description: Bad Request
        404:
          schema:
            type: string
          description: User not found
        500:
          schema:
            type: string
          description: Server error

schemes:
  - https
  - http
